### PR TITLE
implement a tooltip on the title 

### LINKED ISSUE #132: Add tooltip to the demo chart title and add sex-related info in subtitle
Related to #107.
> - When making selection on gender, I was expecting all charts to change based on aggregation, but the bottom right chart doesn't. It will be good to indicate that the bottom right chart is for both genders and all age groups.

### PR DESCRIPTION
**Pull request by billwan96**
to show demo plot does not support filtering on sex and age
closes #132
relates #135

### CODE REVIEW

**Review by SoloSynth1 — COMMENTED** [review]
@billwan96 I think instead of making the tooltip to appear on the title, we can add info icon at the end of the title and make the tooltip shows up there. Also, I think it would help user to understand the icon is doing something special [if the cursor changes to pointer when hovering the icon](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/tooltip/).

**Comment by billwan96** [comment]
That's a great point @SoloSynth1, I am thinking since we will be adding that we only show both sexes and overall age groups in the subtitle, I am thinking if it would be nicer to implement the tooltip in the subtitle. But adding an icon is a great idea too.

**Comment by SoloSynth1** [comment]
I don't have a big preference on this tbh. As long as there is a clear indication for users to realize there are some forms of interactivity on hovering then I think either one works.

Btw it looks like dbc has [built-in support with bootstrap icons and font-awesome icons](https://dash-bootstrap-components.opensource.faculty.ai/docs/icons/), might worth to take a look.

**Comment by billwan96** [comment]
> I don't have a big preference on this tbh. As long as there is a clear indication for users to realize there are some forms of interactivity on hovering then I think either one works.
> 
> Btw it looks like dbc has [built-in support with bootstrap icons and font-awesome icons](https://dash-bootstrap-components.opensource.faculty.ai/docs/icons/), might worth to take a look.

Thanks for the reference, the icons look nice. I think I will go for this

**Comment by SoloSynth1** [comment]
@billwan96 the styling is off, I will look into that tomorrow
image

**Comment by SoloSynth1** [comment]
Also closes #146 upon merge.

**Comment by SoloSynth1** [comment]
Added commits so now there are tooltips for main chart, opioid chart and two aggregated value cards. This will close #121 and close #131 as well.

**Review by SoloSynth1 — APPROVED** [review]
LGTM. Thanks @billwan96 for this awesome tooltip!

**Pull request merged**
