### PR TITLE
Re-do data preprocessing script to make each column a feature

### PR DESCRIPTION
**Pull request by SoloSynth1**
This PR rewrites the data preprocessing script for extracting data from excel spreadsheet into usable format.

### CODE REVIEW

**Review by jinyz8888 — DISMISSED** [review]
both overall.csv and specific.csv should be okay for the first three overall cards

**Comment by SoloSynth1** [comment]
The preprocessing script should be complete in the latest commit. Marking this PR ready for review.

This closes #36.

**Review by jinyz8888 — APPROVED** [review]
Perfect!

**Comment by SoloSynth1** [comment]
Thanks @jinyz8888 for the review. Merging this into `main`.

**Pull request merged**
