### PR TITLE
update demo

### PR DESCRIPTION
**Pull request by jinyz8888**
Update demo including all changes in Milestone 3

### CODE REVIEW

**Review by AlysenTownsley — CHANGES_REQUESTED** [review]
This is me being picky, so please feel free to ignore if you disagree, but could we make the following changes: 
1. Is it possible to record only the dashboard (rather than the full screen), so your other browser tabs are not visible? 
2. Can we show the selection feature similar to what Orix did in the first gif, where you can highlight and area on the plot and filter to that selection? 
3. Keep as short as possible (target 30 seconds max).

**Comment by jinyz8888** [comment]
For 1 and 3, I can try them. But for 2, I have an issue when highlight the area on the plot, when I highlighted an area, it displayed weird.

**Comment by jinyz8888** [comment]
updated! Now it’s 25 seconds, and focused on our dashboard, also highlighted some areas in the plot

**Review by AlysenTownsley — APPROVED** [review]
Requested changes implemented.

**Pull request merged**
