### PR TITLE
Improve the styling of the sidebar

### LINKED ISSUE #78: increase spaces between filters and the footer

### PR DESCRIPTION
**Pull request by billwan96**
This PR updates the css file related to the sidebar:
- make the tooltip not overlapping with the title
- add more space between each selection
- add more space before the footer

closes #78

### CODE REVIEW

**Comment by AlysenTownsley** [comment]
A few thoughts for consideration:
- Would it look better to have the Age Group and Sex filter next to each other as they are the same filter type?
- The title text has a straight line underneath which separates it from the filters. Can we add the same type of line between the filter and the footnote, instead of having extra spaces there?

**Comment by billwan96** [comment]
> A few thoughts for consideration:
> 
> * Would it look better to have the Age Group and Sex filter next to each other as they are the same filter type?
> * The title text has a straight line underneath which separates it from the filters. Can we add the same type of line between the filter and the footnote, instead of having extra spaces there?


Thank you for the comment @AlysenTownsley 
I come up with this.
Screenshot 2024-04-13 at 10 53 09 AM

Not sure if we still want the separation between the footer and the filters, though it was in our issue.

**Comment by AlysenTownsley** [comment]
The screenshot looks good, thanks Bill

**Comment by SoloSynth1** [comment]
Can see there would likely be conflicts with the latest merge from #87. I'm merging HEAD to this branch.

**Comment by SoloSynth1** [comment]
This closes #93 as well as the filter for drug type now uses multidropdown.

**Comment by SoloSynth1** [comment]
Also closes #95 and #90 as the opinion "Any opioid" has been removed.

Callback functions need to be updated though.

**Review by SoloSynth1 — APPROVED** [review]
LGTM. Thanks @billwan96 for the hard work!

**Comment by SoloSynth1** [comment]
Merging this into `main`.

**Pull request merged**
