### PR TITLE
add code of conduct

### PR DESCRIPTION
**Pull request by jinyz8888**

### CODE REVIEW

**Review by SoloSynth1 — COMMENTED** [review]
@jinyz8888 If I understand it correctly this CoC is based on Contributor Covenant, which the latest version is [v2.1](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) instead of v1.4.

Personally i prefer the updated version as it is more precise in what it sets out to achieve, but I would also be perfectly fine even if we don't use the new version. What's your thought on this?

**Comment by SoloSynth1** [comment]
This close #5 upon merging into `main`.

**Comment by billwan96** [comment]
I agree with @SoloSynth1 that it would be nicer if we use the latest version.

**Review by SoloSynth1 — APPROVED** [review]
LGTM. Thanks @jinyz8888 !

**Pull request merged**
