### PR TITLE
fix: Updated opioid plot to reflect instructor feedback

### LINKED ISSUE #80: Remove opioids from the opioid card and change the title to "polysubstances ..."

### PR DESCRIPTION
**Pull request by AlysenTownsley**
closes #80 
relates #74 

Summary of changes:
1. Changed plot title: “Percentage of Deaths Related to Any Opioid” was changed to “Percentage of Overdose Deaths Involving Opioids as a Secondary Factor”
2. Changed plot type to line (female) + dashed line (males) from scatter plot with OLS trendline. 
3. Updated plot to not show the opioid drug class lines (Prescription opioids, Synthetic opioids, or Heroin). Defualt behaviour is to show lines for all other drug types.

### CODE REVIEW

**Review by billwan96 — COMMENTED** [review]
Looks great to me! thanks @AlysenTownsley

**Review by billwan96 — APPROVED** [review]

**Comment by SoloSynth1** [comment]
Also closes #89.

**Review by SoloSynth1 — APPROVED** [review]
LGTM. Thanks @AlysenTownsley for the hard work!

**Comment by SoloSynth1** [comment]
Merging this into `main`.

**Pull request merged**
