### PR TITLE
This commit add a eda notebook for better understanding of the data

### LINKED ISSUE #9: notebooks/ (optional: if you start doing EDA, include your notebooks in this folder)
rubric={reasoning:5}

It is beneficial to take the first few steps in the app development already and push your code to GitHub. This can be very basic, like a general skeleton of the app code with a few components / widgets even if they are not yet linked together. The important part is to make sure everyone in the team can run the basic app on their local machine. This will make sure you can hit the ground running for the next milestone and don't have to deal with any setup issues. If you are doing any EDA on the data, please push those notebooks to the notebooks/ directory. You can also start planning ahead for who will do what next week and create additional issues to capture the ideas you have for the app, so that they don't get lost.

### PR DESCRIPTION
**Pull request by billwan96**
closes #9

### CODE REVIEW

**Comment by billwan96** [comment]
I have used plotly to create these plots, and these are just very basic plots so they aren't the same plot type as proposed. But I guess this is still good for us to understand the trend, or have a brief understanding

When creating these plot I have installed additional package:
1. pip install pandas openpyxl
2. pip install --upgrade nbformat

**Comment by SoloSynth1** [comment]
Let's add `pandas` and `openpyxl ` to the `environment.yml`. Since our data is stored inside excel spreadsheet, we will need these packages to read the data in our data processing pipelines.

However, as we are using `conda` right now, it would be best if we can install these packages using `conda` instead of `pip`.

**Review by SoloSynth1 — COMMENTED** [review]
Let's add `pandas`, `openpyxl` and `nbformat` to the `environment.yml`. Since our data is stored inside excel spreadsheet, we will need these packages to read the data in our data processing pipelines.

However, as we are using `conda` right now, it would be best if we can install these packages using `conda` instead of `pip`.

**Comment by billwan96** [comment]
that makes sense, thanks for pointing out!

**Review by AlysenTownsley — APPROVED** [review]
Reviewed and approved.

**Pull request merged**
